### ISSUE TITLE
Is this still active?

### ISSUE THREAD

**Issue by rayanmargham** [Kinnay/Wii-U-Firmware-Emulator#14]
I 100% wanna see this overtake cemu because of not just being open source, but actually running the wii u menu too!

**Comment by kinnay** [comment]
Hey,

This emulator will never be able to run games like Cemu. It is way too slow for that. This emulator has a different goal anyway, which is system emulation (to learn more about the Wii U) rather than emulating games.

If you are interested in open source emulators, check out [decaf-emu](https://github.com/decaf-emu/decaf-emu), which is really nice and even able to play some games.
